config/routes.rb
Rails.application.routes.draw do
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get 'people/search', to: 'people#search', as: 'search_people'
  get 'search', to: 'people#search', as: 'search_people'


  # a route for the search action 
  resources :people do
    collection do
      post 'search'
    end
  end
  
  get 'today', to: 'people#tbirthdays'

  # Defines the root path route ("/")
  root "people#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
    #validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  def index
    # if params[:q].present?
    #   @people = search
    # else
      @people = Person.all
    # end
  end

  def tbirthdays
    @today_people = find_people_with_birthday_today
  end
  
  # def search
  #   @people = Person.where("name LIKE ? OR phone LIKE ? OR birthday = ?", "%#{params[:q]}%", "%#{params[:q]}%", params[:q])
  #   render :index
  # end

  # def search
  #   render :index
  # end

  def search
    @search_results = Person.where("name LIKE ? OR phone LIKE ? OR birthday LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    render :search
  end
  
  
  
  def birthdays
    @today_people = find_people_with_birthday_today
  end

  def show
    @person = Person.find(params[:id])
  end
  


  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  
  def set_person
    if params[:id] == "search"
      @person = Person.find_by(name: params[:q])
      if @person.nil?
        # handle the case where no person was found for the search query
      end
    else
      @person = Person.find(params[:id])
    end
  end
  


 
  

  def person_params
    params.require(:person).permit(:name, :phone, :email, :gender, :birthday)
  end

  def find_people_with_birthday_today
    Person.where("strftime('%m', birthday) = ? AND strftime('%d', birthday) = ?", Date.today.strftime('%m'), Date.today.strftime('%d'))
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to "Create New Person", new_person_path %>
  <%= link_to 'Today\'s Birthdays', '/today' %>
  <%= link_to 'Search', '/search' %>
  <%= link_to ' Home Page', '/' %>
  
  
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
  <%= form.label :gender %>
  <%= form.select :gender, options_for_select([['Male', 'male'], ['Female', 'female']]) %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= person.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= person.birthday %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>
<h3>Welcome to the BD App</h3>

<%= form_tag search_people_path, method: :get, id: 'search-form' do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>
<hr />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Gender</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%= person.birthday %></td>
        <td><%= person.gender %></td>
        <td><%= link_to "Show this person", person %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/search.html.erb
<br />
<br />
<%= form_tag search_people_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by name, phone, or date of birth" %>
  <%= submit_tag "Search" %>
<% end %>

<% if @search_results.present? %>
  <h2>Search Results:</h2>
    <hr />
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Birthday</th>
        </tr>
      </thead>
      <tbody>
        <% @search_results.each do |person| %>
          <tr>
            <td><%= person.name %></td>
            <td><%= person.phone %></td>
            <td><%= person.birthday %></td>
            <td><%= link_to "Show this person", person %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/people/tbirthdays.html.erb
<h1>Birthdays today <%= Date.today.strftime("%B %d") %></h1>

<% if @today_people.present? %>
  <ul>
    <% @today_people.each do |person| %>
      <li><%= person.name %><span> --- <%=person.phone%></span></li>
    <% end %>
  </ul>
<% else %>
  <p>No birthdays today</p>
<% end %>